package com.devbangs.onedevs.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Generated by art/gen_theme.py from the OneDevs master artwork. Do not edit by
// hand. Surfaces are absolute — pure white and true black — the blue ramp
// follows the mark's measured hue rather than one held hue, and surfaceTint
// equals surface so no tonal overlay ever tints a surface. The generator
// asserts WCAG AA on every on-colour pair before writing this file.

private val lightPrimary = Color(0xFF004EE7)
private val lightOnPrimary = Color(0xFFFFFFFF)
private val lightPrimaryContainer = Color(0xFFD7E2FF)
private val lightOnPrimaryContainer = Color(0xFF001579)
private val lightSecondary = Color(0xFF4C5E88)
private val lightOnSecondary = Color(0xFFFFFFFF)
private val lightSecondaryContainer = Color(0xFFE9EDFF)
private val lightOnSecondaryContainer = Color(0xFF0A264A)
private val lightTertiary = Color(0xFF7A5900)
private val lightOnTertiary = Color(0xFFFFFFFF)
private val lightTertiaryContainer = Color(0xFFFFDEA9)
private val lightOnTertiaryContainer = Color(0xFF322300)
private val lightError = Color(0xFFB4271F)
private val lightOnError = Color(0xFFFFFFFF)
private val lightErrorContainer = Color(0xFFFFDAD2)
private val lightOnErrorContainer = Color(0xFF510800)
private val lightBackground = Color(0xFFFFFFFF)
private val lightOnBackground = Color(0xFF1B1B1B)
private val lightSurface = Color(0xFFFFFFFF)
private val lightOnSurface = Color(0xFF1B1B1B)
private val lightSurfaceVariant = Color(0xFFEEEEEE)
private val lightOnSurfaceVariant = Color(0xFF5E5E5E)
private val lightOutline = Color(0xFF777777)
private val lightOutlineVariant = Color(0xFFE2E2E2)
private val lightInverseSurface = Color(0xFF303030)
private val lightInverseOnSurface = Color(0xFFF1F1F1)
private val lightInversePrimary = Color(0xFF7FABFF)
private val lightScrim = Color(0xFF000000)
private val lightSurfaceDim = Color(0xFFE2E2E2)
private val lightSurfaceBright = Color(0xFFFFFFFF)
private val lightSurfaceContainerLowest = Color(0xFFFFFFFF)
private val lightSurfaceContainerLow = Color(0xFFF9F9F9)
private val lightSurfaceContainer = Color(0xFFF3F3F3)
private val lightSurfaceContainerHigh = Color(0xFFEEEEEE)
private val lightSurfaceContainerHighest = Color(0xFFE8E8E8)
private val lightSurfaceTint = Color(0xFFFFFFFF)

private val darkPrimary = Color(0xFF3A90FF)
private val darkOnPrimary = Color(0xFF000C61)
private val darkPrimaryContainer = Color(0xFF002AA5)
private val darkOnPrimaryContainer = Color(0xFFD7E2FF)
private val darkSecondary = Color(0xFF9AAAD9)
private val darkOnSecondary = Color(0xFF0A264A)
private val darkSecondaryContainer = Color(0xFF263B62)
private val darkOnSecondaryContainer = Color(0xFFD9E2FF)
private val darkTertiary = Color(0xFFD6A334)
private val darkOnTertiary = Color(0xFF322300)
private val darkTertiaryContainer = Color(0xFF4E3800)
private val darkOnTertiaryContainer = Color(0xFFFFDEA9)
private val darkError = Color(0xFFFF8A75)
private val darkOnError = Color(0xFF510800)
private val darkErrorContainer = Color(0xFF7E0006)
private val darkOnErrorContainer = Color(0xFFFFDAD2)
private val darkBackground = Color(0xFF000000)
private val darkOnBackground = Color(0xFFF1F1F1)
private val darkSurface = Color(0xFF000000)
private val darkOnSurface = Color(0xFFF1F1F1)
private val darkSurfaceVariant = Color(0xFF303030)
private val darkOnSurfaceVariant = Color(0xFFABABAB)
private val darkOutline = Color(0xFF919191)
private val darkOutlineVariant = Color(0xFF393939)
private val darkInverseSurface = Color(0xFFF1F1F1)
private val darkInverseOnSurface = Color(0xFF303030)
private val darkInversePrimary = Color(0xFF004EE7)
private val darkScrim = Color(0xFF000000)
private val darkSurfaceDim = Color(0xFF000000)
private val darkSurfaceBright = Color(0xFF393939)
private val darkSurfaceContainerLowest = Color(0xFF000000)
private val darkSurfaceContainerLow = Color(0xFF0E0E0E)
private val darkSurfaceContainer = Color(0xFF131313)
private val darkSurfaceContainerHigh = Color(0xFF1B1B1B)
private val darkSurfaceContainerHighest = Color(0xFF1F1F1F)
private val darkSurfaceTint = Color(0xFF000000)

/**
 * The icon's container blue, measured off the master artwork. DevBot's plate and
 * the splash icon background share it, so the launcher and the app carry the
 * same deep colour. Fixed in both themes: the asset is a white shell, and this
 * is what it is legible against.
 */
internal val brandNavy = Color(0xFF03106B)

/**
 * The tint behind top-bar controls: primary over the page, 5% in light and 20%
 * on true black where the same 5% would be invisible. Material has no role for
 * "a container that is brand-coloured but is not a button", and reaching for
 * surfaceContainerHigh instead put a grey slab on a blue brand. Read this
 * through OneDevsTheme's LocalOneDevsColors rather than picking a side by hand.
 */
internal val brandTintLight = Color(0xFFF2F6FE)
internal val brandTintDark = Color(0xFF0C1D33)

/**
 * One accent per launch action. The solid carries a glyph or a label, the
 * tint backs the card, and onSolid is whatever stays readable on the solid.
 * Generated, not chosen: the solid is the most saturated tone of the seed
 * hue that still clears 4.5:1 against the page it sits on, which is why the
 * live accent lands deeper than the mockup's mint -- mint carries no label.
 */
internal val accentTestingLight = Accent(
    solid = Color(0xFF005EB3),
    onSolid = Color(0xFFFFFFFF),
    tint = Color(0xFFEDF4FA),
)

internal val accentTestingDark = Accent(
    solid = Color(0xFF3D90FF),
    onSolid = Color(0xFF001B3C),
    tint = Color(0xFF0D2038),
)

internal val accentMissionLight = Accent(
    solid = Color(0xFF773BCA),
    onSolid = Color(0xFFFFFFFF),
    tint = Color(0xFFF5F1FB),
)

internal val accentMissionDark = Accent(
    solid = Color(0xFFB070FF),
    onSolid = Color(0xFF23005C),
    tint = Color(0xFF271938),
)

internal val accentLiveLight = Accent(
    solid = Color(0xFF006C4F),
    onSolid = Color(0xFFFFFFFF),
    tint = Color(0xFFEDF5F3),
)

internal val accentLiveDark = Accent(
    solid = Color(0xFF00A47A),
    onSolid = Color(0xFF002116),
    tint = Color(0xFF00241B),
)

internal val accentFeedbackLight = Accent(
    solid = Color(0xFF4E47DC),
    onSolid = Color(0xFFFFFFFF),
    tint = Color(0xFFF3F2FD),
)

internal val accentFeedbackDark = Accent(
    solid = Color(0xFF937DFF),
    onSolid = Color(0xFF000E5E),
    tint = Color(0xFF201C38),
)

internal val accentCommunityLight = Accent(
    solid = Color(0xFF006971),
    onSolid = Color(0xFFFFFFFF),
    tint = Color(0xFFEDF4F5),
)

internal val accentCommunityDark = Accent(
    solid = Color(0xFF00A0AD),
    onSolid = Color(0xFF002023),
    tint = Color(0xFF002326),
)

internal val lightScheme = lightColorScheme(
    primary = lightPrimary,
    onPrimary = lightOnPrimary,
    primaryContainer = lightPrimaryContainer,
    onPrimaryContainer = lightOnPrimaryContainer,
    secondary = lightSecondary,
    onSecondary = lightOnSecondary,
    secondaryContainer = lightSecondaryContainer,
    onSecondaryContainer = lightOnSecondaryContainer,
    tertiary = lightTertiary,
    onTertiary = lightOnTertiary,
    tertiaryContainer = lightTertiaryContainer,
    onTertiaryContainer = lightOnTertiaryContainer,
    error = lightError,
    onError = lightOnError,
    errorContainer = lightErrorContainer,
    onErrorContainer = lightOnErrorContainer,
    background = lightBackground,
    onBackground = lightOnBackground,
    surface = lightSurface,
    onSurface = lightOnSurface,
    surfaceVariant = lightSurfaceVariant,
    onSurfaceVariant = lightOnSurfaceVariant,
    outline = lightOutline,
    outlineVariant = lightOutlineVariant,
    inverseSurface = lightInverseSurface,
    inverseOnSurface = lightInverseOnSurface,
    inversePrimary = lightInversePrimary,
    scrim = lightScrim,
    surfaceDim = lightSurfaceDim,
    surfaceBright = lightSurfaceBright,
    surfaceContainerLowest = lightSurfaceContainerLowest,
    surfaceContainerLow = lightSurfaceContainerLow,
    surfaceContainer = lightSurfaceContainer,
    surfaceContainerHigh = lightSurfaceContainerHigh,
    surfaceContainerHighest = lightSurfaceContainerHighest,
    surfaceTint = lightSurfaceTint,
)

internal val darkScheme = darkColorScheme(
    primary = darkPrimary,
    onPrimary = darkOnPrimary,
    primaryContainer = darkPrimaryContainer,
    onPrimaryContainer = darkOnPrimaryContainer,
    secondary = darkSecondary,
    onSecondary = darkOnSecondary,
    secondaryContainer = darkSecondaryContainer,
    onSecondaryContainer = darkOnSecondaryContainer,
    tertiary = darkTertiary,
    onTertiary = darkOnTertiary,
    tertiaryContainer = darkTertiaryContainer,
    onTertiaryContainer = darkOnTertiaryContainer,
    error = darkError,
    onError = darkOnError,
    errorContainer = darkErrorContainer,
    onErrorContainer = darkOnErrorContainer,
    background = darkBackground,
    onBackground = darkOnBackground,
    surface = darkSurface,
    onSurface = darkOnSurface,
    surfaceVariant = darkSurfaceVariant,
    onSurfaceVariant = darkOnSurfaceVariant,
    outline = darkOutline,
    outlineVariant = darkOutlineVariant,
    inverseSurface = darkInverseSurface,
    inverseOnSurface = darkInverseOnSurface,
    inversePrimary = darkInversePrimary,
    scrim = darkScrim,
    surfaceDim = darkSurfaceDim,
    surfaceBright = darkSurfaceBright,
    surfaceContainerLowest = darkSurfaceContainerLowest,
    surfaceContainerLow = darkSurfaceContainerLow,
    surfaceContainer = darkSurfaceContainer,
    surfaceContainerHigh = darkSurfaceContainerHigh,
    surfaceContainerHighest = darkSurfaceContainerHighest,
    surfaceTint = darkSurfaceTint,
)
