package com.devbangs.onedevs.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// Generated by art/gen_theme.py from the OneDevs master artwork. Do not edit by
// hand: primary comes from the icon's blue, secondary from the mark's cyan and
// tertiary from the DevCoin gold, and the generator asserts WCAG AA on every
// on-colour pair before writing this file.

private val lightPrimary = Color(0xFF384CDE)
private val lightOnPrimary = Color(0xFFFFFFFF)
private val lightPrimaryContainer = Color(0xFFE5DEFF)
private val lightOnPrimaryContainer = Color(0xFF001355)
private val lightSecondary = Color(0xFF006972)
private val lightOnSecondary = Color(0xFFFEFFFF)
private val lightSecondaryContainer = Color(0xFF8BF2FF)
private val lightOnSecondaryContainer = Color(0xFF001F23)
private val lightTertiary = Color(0xFF7A5900)
private val lightOnTertiary = Color(0xFFFFFFFE)
private val lightTertiaryContainer = Color(0xFFFFDEA9)
private val lightOnTertiaryContainer = Color(0xFF251A00)
private val lightError = Color(0xFFB4271F)
private val lightOnError = Color(0xFFFFFFFF)
private val lightErrorContainer = Color(0xFFFFDAD2)
private val lightOnErrorContainer = Color(0xFF390C00)
private val lightBackground = Color(0xFFFCFCFF)
private val lightOnBackground = Color(0xFF1C1B20)
private val lightSurface = Color(0xFFFCFCFF)
private val lightOnSurface = Color(0xFF1C1B20)
private val lightSurfaceVariant = Color(0xFFE4E0F0)
private val lightOnSurfaceVariant = Color(0xFF484551)
private val lightOutline = Color(0xFF787583)
private val lightOutlineVariant = Color(0xFFC8C5D3)
private val lightInverseSurface = Color(0xFF313035)
private val lightInverseOnSurface = Color(0xFFF1F0F7)
private val lightInversePrimary = Color(0xFFC9BEFF)
private val lightScrim = Color(0xFF000004)
private val lightSurfaceDim = Color(0xFFDBD9E0)
private val lightSurfaceBright = Color(0xFFFAF8FF)
private val lightSurfaceContainerLowest = Color(0xFFFFFFFF)
private val lightSurfaceContainerLow = Color(0xFFF4F3FA)
private val lightSurfaceContainer = Color(0xFFEEEDF4)
private val lightSurfaceContainerHigh = Color(0xFFE9E7EF)
private val lightSurfaceContainerHighest = Color(0xFFE3E1E9)

private val darkPrimary = Color(0xFFC9BEFF)
private val darkOnPrimary = Color(0xFF002486)
private val darkPrimaryContainer = Color(0xFF0036BB)
private val darkOnPrimaryContainer = Color(0xFFE5DEFF)
private val darkSecondary = Color(0xFF00DBEE)
private val darkOnSecondary = Color(0xFF00363C)
private val darkSecondaryContainer = Color(0xFF004F56)
private val darkOnSecondaryContainer = Color(0xFF8BF2FF)
private val darkTertiary = Color(0xFFF5BE4F)
private val darkOnTertiary = Color(0xFF402D00)
private val darkTertiaryContainer = Color(0xFF5D4200)
private val darkOnTertiaryContainer = Color(0xFFFFDEA9)
private val darkError = Color(0xFFFFB4A5)
private val darkOnError = Color(0xFF690000)
private val darkErrorContainer = Color(0xFF93000B)
private val darkOnErrorContainer = Color(0xFFFFDAD2)
private val darkBackground = Color(0xFF1C1B20)
private val darkOnBackground = Color(0xFFE3E1E9)
private val darkSurface = Color(0xFF1C1B20)
private val darkOnSurface = Color(0xFFE3E1E9)
private val darkSurfaceVariant = Color(0xFF484551)
private val darkOnSurfaceVariant = Color(0xFFC8C5D3)
private val darkOutline = Color(0xFF928F9D)
private val darkOutlineVariant = Color(0xFF484551)
private val darkInverseSurface = Color(0xFFE3E1E9)
private val darkInverseOnSurface = Color(0xFF313035)
private val darkInversePrimary = Color(0xFF384CDE)
private val darkScrim = Color(0xFF000004)
private val darkSurfaceDim = Color(0xFF141318)
private val darkSurfaceBright = Color(0xFF3A383E)
private val darkSurfaceContainerLowest = Color(0xFF0F0D14)
private val darkSurfaceContainerLow = Color(0xFF1C1B20)
private val darkSurfaceContainer = Color(0xFF201F24)
private val darkSurfaceContainerHigh = Color(0xFF2A292F)
private val darkSurfaceContainerHighest = Color(0xFF35343A)

// DevBot keeps his own container colour in both themes: the asset is a white
// shell that reads at 1.26:1 on a light surface and 13:1 on a dark one.
internal val devBotSurface = Color(0xFF141318)

internal val lightScheme = lightColorScheme(
    primary = lightPrimary,
    onPrimary = lightOnPrimary,
    primaryContainer = lightPrimaryContainer,
    onPrimaryContainer = lightOnPrimaryContainer,
    secondary = lightSecondary,
    onSecondary = lightOnSecondary,
    secondaryContainer = lightSecondaryContainer,
    onSecondaryContainer = lightOnSecondaryContainer,
    tertiary = lightTertiary,
    onTertiary = lightOnTertiary,
    tertiaryContainer = lightTertiaryContainer,
    onTertiaryContainer = lightOnTertiaryContainer,
    error = lightError,
    onError = lightOnError,
    errorContainer = lightErrorContainer,
    onErrorContainer = lightOnErrorContainer,
    background = lightBackground,
    onBackground = lightOnBackground,
    surface = lightSurface,
    onSurface = lightOnSurface,
    surfaceVariant = lightSurfaceVariant,
    onSurfaceVariant = lightOnSurfaceVariant,
    outline = lightOutline,
    outlineVariant = lightOutlineVariant,
    inverseSurface = lightInverseSurface,
    inverseOnSurface = lightInverseOnSurface,
    inversePrimary = lightInversePrimary,
    scrim = lightScrim,
    surfaceDim = lightSurfaceDim,
    surfaceBright = lightSurfaceBright,
    surfaceContainerLowest = lightSurfaceContainerLowest,
    surfaceContainerLow = lightSurfaceContainerLow,
    surfaceContainer = lightSurfaceContainer,
    surfaceContainerHigh = lightSurfaceContainerHigh,
    surfaceContainerHighest = lightSurfaceContainerHighest,
)

internal val darkScheme = darkColorScheme(
    primary = darkPrimary,
    onPrimary = darkOnPrimary,
    primaryContainer = darkPrimaryContainer,
    onPrimaryContainer = darkOnPrimaryContainer,
    secondary = darkSecondary,
    onSecondary = darkOnSecondary,
    secondaryContainer = darkSecondaryContainer,
    onSecondaryContainer = darkOnSecondaryContainer,
    tertiary = darkTertiary,
    onTertiary = darkOnTertiary,
    tertiaryContainer = darkTertiaryContainer,
    onTertiaryContainer = darkOnTertiaryContainer,
    error = darkError,
    onError = darkOnError,
    errorContainer = darkErrorContainer,
    onErrorContainer = darkOnErrorContainer,
    background = darkBackground,
    onBackground = darkOnBackground,
    surface = darkSurface,
    onSurface = darkOnSurface,
    surfaceVariant = darkSurfaceVariant,
    onSurfaceVariant = darkOnSurfaceVariant,
    outline = darkOutline,
    outlineVariant = darkOutlineVariant,
    inverseSurface = darkInverseSurface,
    inverseOnSurface = darkInverseOnSurface,
    inversePrimary = darkInversePrimary,
    scrim = darkScrim,
    surfaceDim = darkSurfaceDim,
    surfaceBright = darkSurfaceBright,
    surfaceContainerLowest = darkSurfaceContainerLowest,
    surfaceContainerLow = darkSurfaceContainerLow,
    surfaceContainer = darkSurfaceContainer,
    surfaceContainerHigh = darkSurfaceContainerHigh,
    surfaceContainerHighest = darkSurfaceContainerHighest,
)
