package com.devbangs.onedevs.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * The colours the app needs that Material's scheme has no role for.
 *
 * Both are generated by art/gen_theme.py from the same palette as the scheme,
 * so they move when the brand moves. They live here rather than being read
 * directly because one of them differs by theme, and a component branching on
 * isSystemInDarkTheme would quietly ignore a caller that overrode darkTheme.
 */
/**
 * One launch action's identity. Generated in art/gen_theme.py, where the solid
 * is picked as the most saturated tone of its seed that still carries [onSolid]
 * at 4.5:1 -- which is why the live accent lands deeper than a mint: mint does
 * not carry a label.
 */
@Immutable
data class Accent(
    /** Icon circles, status pills, the arrow button. Carries [onSolid]. */
    val solid: Color,
    /** Whatever sits on [solid]. */
    val onSolid: Color,
    /** The card's backing, the same hue at a whisper. */
    val tint: Color,
)

@Immutable
data class OneDevsColors(
    /** Brand-coloured backing for a control that is not a button. */
    val brandTint: Color,
    /** The icon's container blue. Fixed in both themes; DevBot's plate sits on it. */
    val brandNavy: Color,
    /** Getting an app in front of testers. */
    val testing: Accent,
    /** Spending DevCoins on focused feedback. */
    val mission: Accent,
    /** Publishing to Live Apps, and the verification badges that go with it. */
    val live: Accent,
    /** Reports, bugs, anything said back to a developer. */
    val feedback: Accent,
    /** Helping other developers. */
    val community: Accent,
)

val LocalOneDevsColors = staticCompositionLocalOf {
    OneDevsColors(
        brandTint = brandTintLight,
        brandNavy = brandNavy,
        testing = accentTestingLight,
        mission = accentMissionLight,
        live = accentLiveLight,
        feedback = accentFeedbackLight,
        community = accentCommunityLight,
    )
}

/** Reads like MaterialTheme.colorScheme, and is meant to. */
val oneDevsColors: OneDevsColors
    @Composable @ReadOnlyComposable get() = LocalOneDevsColors.current

@Composable
fun OneDevsTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    content: @Composable () -> Unit,
) {
    CompositionLocalProvider(
        LocalOneDevsColors provides OneDevsColors(
            brandTint = if (darkTheme) brandTintDark else brandTintLight,
            brandNavy = brandNavy,
            testing = if (darkTheme) accentTestingDark else accentTestingLight,
            mission = if (darkTheme) accentMissionDark else accentMissionLight,
            live = if (darkTheme) accentLiveDark else accentLiveLight,
            feedback = if (darkTheme) accentFeedbackDark else accentFeedbackLight,
            community = if (darkTheme) accentCommunityDark else accentCommunityLight,
        ),
    ) {
        MaterialTheme(
            colorScheme = if (darkTheme) darkScheme else lightScheme,
            typography = OneDevsTypography,
            content = content,
        )
    }
}
