package com.devbangs.onedevs.ui.theme

import androidx.compose.foundation.isSystemInDarkTheme
import com.devbangs.onedevs.settings.AppTheme
import com.devbangs.onedevs.settings.ThemeStore
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * The colours the app needs that Material's scheme has no role for.
 *
 * Both are generated by art/gen_theme.py from the same palette as the scheme,
 * so they move when the brand moves. They live here rather than being read
 * directly because one of them differs by theme, and a component branching on
 * isSystemInDarkTheme would quietly ignore a caller that overrode darkTheme.
 */
/**
 * One launch action's identity. Generated in art/gen_theme.py, where the solid
 * is picked as the most saturated tone of its seed that still carries [onSolid]
 * at 4.5:1 -- which is why the live accent lands deeper than a mint: mint does
 * not carry a label.
 */
@Immutable
data class Accent(
    /** Icon circles, status pills, the arrow button. Carries [onSolid]. */
    val solid: Color,
    /** Whatever sits on [solid]. */
    val onSolid: Color,
    /** The card's backing, the same hue at a whisper. */
    val tint: Color,
)

@Immutable
data class OneDevsColors(
    /** Brand-coloured backing for a control that is not a button. */
    val brandTint: Color,
    /** The icon's container blue. Fixed in both themes; DevBot's plate sits on it. */
    val brandNavy: Color,
    /** Getting an app in front of testers. */
    val testing: Accent,
    /** Spending DevCoins on focused feedback. */
    val mission: Accent,
    /** Publishing to Live Apps, and the verification badges that go with it. */
    val live: Accent,
    /** Reports, bugs, anything said back to a developer. */
    val feedback: Accent,
    /** Helping other developers. */
    val community: Accent,
    /** Something that wants looking at before it ships. */
    val caution: Accent,
    /** Something that will stop a release. */
    val critical: Accent,
    /**
     * The page everything sits on: a cool grey in light, true black in dark.
     * Never the colour of a card, so every card stands off it.
     */
    val page: Color = PageLight,
    /** Every card, group and panel: white in light, lifted charcoal in dark. */
    val card: Color = CardLight,
    /** A row or field set into a card: one step back from the card. */
    val well: Color = WellLight,
)

// The elevation system: page, card, well. Hierarchy is carried by fill, not by
// outlines -- a card is a different colour from the page, a row inside it a
// different colour from the card, and nothing needs a hairline to be seen.
private val PageLight = Color(0xFFF1F3F6)
private val CardLight = Color(0xFFFFFFFF)
private val WellLight = Color(0xFFF1F3F6)
private val PageDark = Color(0xFF000000)
private val CardDark = Color(0xFF16181C)
private val WellDark = Color(0xFF22252B)

val LocalOneDevsColors = staticCompositionLocalOf {
    OneDevsColors(
        brandTint = brandTintLight,
        brandNavy = brandNavy,
        testing = accentTestingLight,
        mission = accentMissionLight,
        live = accentLiveLight,
        feedback = accentFeedbackLight,
        community = accentCommunityLight,
        caution = accentCautionLight,
        critical = accentCriticalLight,
    )
}

/** Reads like MaterialTheme.colorScheme, and is meant to. */
val oneDevsColors: OneDevsColors
    @Composable @ReadOnlyComposable get() = LocalOneDevsColors.current

@Composable
fun OneDevsTheme(
    darkTheme: Boolean = when (ThemeStore.current) {
        AppTheme.System -> isSystemInDarkTheme()
        AppTheme.Light -> false
        AppTheme.Dark -> true
    },
    content: @Composable () -> Unit,
) {
    CompositionLocalProvider(
        LocalOneDevsColors provides OneDevsColors(
            brandTint = if (darkTheme) brandTintDark else brandTintLight,
            brandNavy = brandNavy,
            testing = if (darkTheme) accentTestingDark else accentTestingLight,
            mission = if (darkTheme) accentMissionDark else accentMissionLight,
            live = if (darkTheme) accentLiveDark else accentLiveLight,
            feedback = if (darkTheme) accentFeedbackDark else accentFeedbackLight,
            community = if (darkTheme) accentCommunityDark else accentCommunityLight,
            caution = if (darkTheme) accentCautionDark else accentCautionLight,
            critical = if (darkTheme) accentCriticalDark else accentCriticalLight,
            page = if (darkTheme) PageDark else PageLight,
            card = if (darkTheme) CardDark else CardLight,
            well = if (darkTheme) WellDark else WellLight,
        ),
    ) {
        val scheme = if (darkTheme) darkScheme else lightScheme
        MaterialTheme(
            // The page is the background; surface stays the card's own white
            // or black for the components that draw on it.
            // The container greys step up from the card, so a chip, a note or
            // a disabled button reads on a card and on the page alike.
            colorScheme = if (darkTheme) {
                scheme.copy(
                    background = PageDark,
                    surfaceContainer = Color(0xFF1C1F24),
                    surfaceContainerHigh = Color(0xFF25282E),
                    surfaceContainerHighest = Color(0xFF2D3138),
                )
            } else {
                scheme.copy(
                    background = PageLight,
                    surfaceContainer = Color(0xFFEBEEF2),
                    surfaceContainerHigh = Color(0xFFE4E8EE),
                    surfaceContainerHighest = Color(0xFFDCE1E8),
                )
            },
            typography = OneDevsTypography,
            content = content,
        )
    }
}
